

cc_test(
    name = "member-test",
    srcs = ["member_test.cc","member.h"],
    copts = ["-Iexternal/gtest",
             "-Iexternal/gtest/include",
             ],
    deps = ["@gtest//:main",],
)